### ISSUE TITLE
Long sentences are not being removed apparently

### ISSUE THREAD

**Issue by cgr71ii** [bitextor/bifixer#17]
Hi!

Either `monofixer` or `bifixer` should remove long sentences when the number of words is greater than 5000:
https://github.com/bitextor/bifixer/blob/1a91e3eb47b2c4e7de9d6812fe25ed1bd5f4e9d4/bifixer/monofixer.py#L195
https://github.com/bitextor/bifixer/blob/1a91e3eb47b2c4e7de9d6812fe25ed1bd5f4e9d4/bifixer/bifixer.py#L215

The problem is that, apparently, it seems that it is not working:

```bash
pip3 install bifixer==0.8.3
```

```bash
# monofixer

python -c "print('asd'); print(' '.join(['a']*6000)); print('asd')" \
  | monofixer --scol 1 --ignore_duplicates  -q - - es \
  | wc -w
# 6002

python -c "print('asd'); print(' '.join(['a']*6000)); print('asd')" \
  | monofixer --scol 1 --ignore_duplicates --ignore_long -q - - es \
  | wc -w
# 6002
```

```bash
# bifixer

python -c "print('asd\tasd'); print('asd\t' + ' '.join(['a']*6000)); print('asd\tasd')" \
  | bifixer --scol 1 --tcol 2 --ignore_duplicates  -q - - en es \
  | wc -w
# 6005

python -c "print('asd\tasd'); print('asd\t' + ' '.join(['a']*6000)); print('asd\tasd')" \
  | bifixer --scol 1 --tcol 2 --ignore_long --ignore_duplicates  -q - - en es \
  | wc -w
# 6005
```

Am I doing something wrong?

Thank you!

**Comment by mbanon** [comment]
Long sentences are not being removed, they are just ignored (not processed, but outputted).

It's not correct at the documentation, I'm fixing it.

**Comment by cgr71ii** [comment]
Oh! Ok, thank you!
