### ISSUE TITLE
Bifixer doesn't see input file

### ISSUE THREAD

**Issue by Syrkovski** [bitextor/bifixer#2]
Hello, I tried use bifixer, but I have error.
The command I used:
> python3.7 bifixer/bifixer.py --scol 1 --tcol 2 --ignore_duplicates corpus corpus.bifixed en zh

The error:
> bifixer.py: error: argument input: can't open 'corpus': [Errno 2] No such file or directory: 'corpus'

I have the corpus.en and corpus.zh, but bifixer doesn't see it.

**Comment by mbanon** [comment]
Hi @Syrkovski .
It must be in a single file  (`paste corpus.en  corpus.zh > corpus`)

**Comment by Syrkovski** [comment]
Thank you
