### ISSUE TITLE
&#9; introduces tabs in tsv output

### ISSUE THREAD

**Issue by jelmervdl** [bitextor/bifixer#4]
When running bifixer with the default options (as we do in Paracrawl) it will decode encoded html entities. Including encoded tab characters. This messes up the output, since that's tab separated.

Test case (with `tr` added on the back to make the tab characters visible)
```bash
echo -e "a\tb\tc\tFlavor:&#9;salty & light" | bifixer - - en en | tr '\t' '^'
```
yields (note the `^` in "Flavor:^salty")
```
a^b^c^Flavor:^salty & light^d39f54ca9c3055f8^1
```

I expect [`html.unescape(..)`](https://github.com/bitextor/bifixer/blob/master/bifixer/restorative_cleaning.py#L647) is to blame (but didn't test that!) Maybe a way to fix it would be to move [`re.sub(' +', ' ', ..)`](https://github.com/bitextor/bifixer/blob/master/bifixer/restorative_cleaning.py#L639) down a bit and include tabs in that as well, i.e. `re.sub('\s+', ' ', ..)` (and then you don't need to add the \n to strip() afterwards anymore either)

(Thanks @mksifakis for figuring this out!)

**Comment by ZJaume** [comment]
The problem comes from `ftfy` that is fixing unicode and therefore it replaces it by tab. We are still thinking how to deal with this.

https://www.codetable.net/decimal/9
