### ISSUE TITLE
Bifixer Indexerror: list index out of range

### ISSUE THREAD

**Issue by jokinlasa** [bitextor/bifixer#7]
After installing the bifixer software, I tried to run the test for testing if the software was working correctly and I get this Error:

`/bifixer-master/tests$ pytest
================================================ test session starts ================================================
platform linux -- Python 3.6.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/adminitzuli/ml-bifixer-jokin/bifixer-master/tests
collected 0 items / 1 error

====================================================== ERRORS =======================================================
_________________________________________ ERROR collecting test_bifixer.py __________________________________________
test_bifixer.py:116: in <module>
    class TestOrthoFix:
test_bifixer.py:118: in TestOrthoFix
    replacements_es = restorative_cleaning.getReplacements("es")
../bifixer/restorative_cleaning.py:612: in getReplacements
    replacements[field[0].strip()] = field[1].strip()
E   IndexError: list index out of range
============================================== short test summary info ==============================================
ERROR test_bifixer.py - IndexError: list index out of range
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================= 1 error in 0.34s ==================================================
`

I get the same error trying to clean my memory, I have not had problems with the installation, and the python version is on point.
Have any of you experienced this error or any suggestions to solve it?

Thank you,

Jokin

**Comment by ZJaume** [comment]
The tests are working for me, have you changed any of the replacements files? The error is telling that a replacement file has a missing column.

**Comment by ZJaume** [comment]
Hi Jokin,

Sorry for the misunderstanding, I hadn't the latest changes on my machine. After pulling them correctly I noticed that there were some replacements being separated by space instead of tab. Pushed a commit that fixes it.

Regarding your second question, the error is telling you that, probably the 110582 does not contain the target sentence or has less fields than it is supposed to have.
